### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertBefore' of undefined

### ISSUE THREAD

**Issue by rgbskills** [abe33/atom-tree-view-breadcrumb#11]
1. installed tree-view-breadcrumbs
2. settings-> clicked on "display project root", keep breadcrumbs visible

**Atom Version**: 0.172.0
**System**: Microsoft Windows 8.1
**Thrown From**: [tree-view-breadcrumb](https://github.com/abe33/atom-tree-view-breadcrumb) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'insertBefore' of undefined

```
At /c:/Users/Zoltan%20Benko/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:133

TypeError: Cannot read property 'insertBefore' of undefined
  at tree-view-breadcrumb.BreadcrumbElement.attach (c:\Users\Zoltan Benko\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:73:21)
  at tree-view-breadcrumb.BreadcrumbElement.show (c:\Users\Zoltan Benko\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:63:6)
  at c:\Users\Zoltan Benko\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:37:10
  at c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\src\config.js:620:16
  at c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\src\config.js:637:20
  at Emitter.module.exports.Emitter.emit (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\src\config.js:748:29)
  at Config.module.exports.Config.setRawValue (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\src\config.js:614:19)
  at Config.module.exports.Config.set (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\src\config.js:230:14)
  at SettingsPanel.module.exports.SettingsPanel.set (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\settings-view\lib\settings-panel.js:185:28)
  at setNewValue (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\settings-view\lib\settings-panel.js:131:28)
  at HTMLInputElement.<anonymous> (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\settings-view\lib\settings-panel.js:137:22)
  at HTMLInputElement.jQuery.event.dispatch (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\autocomplete\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at HTMLInputElement.elemData.handle (c:\Users\Zoltan Benko\AppData\Local\atom\app-0.172.0\resources\app\node_modules\autocomplete\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -1:47.5 core:save (atom-text-editor.editor)
 17x -1:47.0 core:move-down (atom-text-editor.editor)
     -1:45.6 editor:move-to-end-of-screen-line (atom-text-editor.editor)
 55x -1:45.3 core:move-down (atom-text-editor.editor)
 88x -1:42.8 core:move-up (atom-text-editor.editor)
  5x -1:38.8 core:move-down (atom-text-editor.editor)
     -1:36.4 command-palette:toggle (atom-text-editor.editor)
  3x -1:34.1 core:move-down (atom-text-editor.editor.mini)
     -1:33.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:33.4 core:cancel (atom-text-editor.editor.mini)
 24x -1:32.5 core:move-down (atom-text-editor.editor)
     -1:22.2 command-palette:toggle (atom-text-editor.editor)
  7x -1:13.1 core:backspace (atom-text-editor.editor.mini)
     -1:08.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:08.8 core:cancel (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  },
  "tree-view-breadcrumb": {
    "displayProjectRoot": true,
    "keepBreadcrumbVisible": true
  }
}
```

### Installed Packages

```coffee
# User
monokai, v0.12.0
tree-view-breadcrumb, v0.4.0
tree-view-open-files, v0.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Thanks for the report I'll try to fix that soon.
