### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by anisylen** [abe33/atom-tree-view-breadcrumb#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [tree-view-breadcrumb](https://github.com/abe33/atom-tree-view-breadcrumb) package, v0.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/anirudh/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:138

TypeError: Cannot read property 'getBoundingClientRect' of null
  at tree-view-breadcrumb.BreadcrumbElement.scrollToItem (/Users/anirudh/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:138:18)
  at subscriptions.add.subscribeTo.click (/Users/anirudh/.atom/packages/tree-view-breadcrumb/lib/breadcrumb-element.coffee:27:10)
  at /Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:128:18
  at tree-view-breadcrumb.module.exports.EventsDelegation.eachSelector (/Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:144:13)
  at /Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:122:22
  at tree-view-breadcrumb.module.exports.EventsDelegation.nodeAndItsAncestors (/Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:169:7)
  at tree-view-breadcrumb.module.exports.EventsDelegation.eachSelectorFromTarget (/Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:118:19)
  at HTMLDivElement.listener (/Users/anirudh/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/mixins/events-delegation.js:105:15)

```

### Commands

```
     -1:07.0 command-palette:toggle (input.hidden-input)
  4x -0:59.6.0 core:backspace (input.hidden-input)
     -0:53.1.0 core:confirm (input.hidden-input)
     -0:53.1.0 git-plus:checkout (input.hidden-input)
     -0:49 editor:consolidate-selections (input.hidden-input)
     -0:49 core:cancel (input.hidden-input)
     -0:46.7.0 command-palette:toggle (input.hidden-input)
     -0:43.7.0 core:confirm (input.hidden-input)
     -0:43.7.0 git-plus:fetch (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "travis-ci-status",
      "remember-session",
      "project-view",
      "git-control"
    ],
    "ignoredNames": [
      "*.p12",
      ""
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "tree-view-breadcrumb": {
    "displayProjectRoot": true,
    "keepBreadcrumbVisible": true,
    "pathStyle": true,
    "scrollbarStyle": "thin"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-html-preview, v0.1.11
atom-material-syntax, v0.2.2
atom-material-ui, v0.5.13
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
emmet, v2.3.12
figlet, v0.4.0
file-icons, v1.6.3
git-log, v0.4.1
git-plus, v5.3.4
highlight-selected, v0.10.1
linter, v1.3.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
minimap, v4.12.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.1
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.3
minimap-selection, v4.3.0
pigments, v0.9.3
project-manager, v1.15.11
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
tabs-to-spaces, v0.11.0
tree-view-breadcrumb, v0.6.1
tree-view-git-branch, v0.0.2

# Dev
No dev packages
```

**Comment by anisylen** [comment]
Happened when I clicked the repo icon in the breadcrumb
