### ISSUE TITLE
Failed to load the tree-view-breadcrumb package

### ISSUE THREAD

**Issue by rugk** [abe33/atom-tree-view-breadcrumb#20]
[Enter steps to reproduce below:]

1. Install latest version.

**Atom Version**: 1.0.15
**System**: Windows 7
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Failed to load the tree-view-breadcrumb package

```
At Cannot read property 'includeInto' of undefined

TypeError: Cannot read property 'includeInto' of undefined
    at D:\Users\%username%\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:5:19
    at Object.<anonymous> (D:\Users\%username%\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:5:3)
    at Object.<anonymous> (D:\Users\%username%\.atom\packages\tree-view-breadcrumb\lib\breadcrumb-element.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (D:\Users\%username%\.atom\packages\tree-view-breadcrumb\lib\tree-view-breadcrumb.coffee:1:21)
```

### Commands

```
     -9:48.3.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -8:01.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-emojis",
      "switcheroo",
      "markdown-table-formatter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.16.2
aligner-php, v1.0.0
aligner-scss, v1.1.0
autocomplete-php, v0.3.7
autohide-tree-view, v0.24.3
color-picker, v2.0.12
compare-files, v0.6.2
editor-stats, v0.17.0
figlet, v0.4.0
file-icons, v1.6.9
highlight-column, v0.5.0
highlight-selected, v0.10.1
keyboard-localization, v1.4.8
language-autoit, v0.2.1
language-batch, v0.3.3
language-ini, v1.12.0
language-pascal, v0.8.0
line-count-status, v0.0.1
line-diff-details, v1.1.2
linter, v1.6.0
linter-alex, v1.2.2
linter-htmlhint, v0.1.1
linter-php, v1.0.3
markdown-preview-opener, v0.1.1
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
php-cs-fixer, v2.4.0
pigments, v0.15.0
tabs-to-spaces, v0.11.1
tidy-markdown, v1.0.0
tree-view-background, v0.4.0
tree-view-breadcrumb, v0.6.3

# Dev
No dev packages
```

**Comment by abe33** [comment]
This looks like atom/atom#8891 to me.
